hopco:
  target: prod
  outputs:
    dev:
      type: snowflake
      account: VR02787

      # User/password auth
      user: WRANGLER
      password: fn9caNpb672X9&ZR

      role: WH_USER
      database: HOPCO
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 5
      client_session_keep_alive: False
      query_tag: dbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None
